app:
    build: ./app
    links:
        - redis
    ports:
        - 80:8001
    environment:
        101QS_DEBUG: True
        PYTHONUNBUFFERED: True
    env_file:
        ./configs/email.env

redis:
    image: redis
    volumes:
        - data:/data
