app:
    build: ./app
    links:
        - redis
    ports:
        - 10177:8001
    environment:
        # 101QS_DEBUG: ENABLED
        # 101QS_RELOAD: ENABLED
        PYTHONUNBUFFERED: ENABLED
    env_file:
        - ./configs/email.env
        - ./configs/hmac.env
        - ./configs/mailgun.env

redis:
    image: redis
    volumes:
        - ./data:/data
