proxy:
    build: ./proxy
    links:
        - api
        - web
    ports:
        - 80:80

api:
    build: ./api
    links:
        - redis
    expose:
        - 8001
    env_file:
        - ./configs/email.env

web:
    build: ./web
    expose:
        - 80

redis:
    image: redis
    volumes:
        - data:/data
