web:
    image: nginx
    ports:
        - 80:80
    links:
        - api
    volumes:
        - nginx/sites-enabled:/etc/nginx/conf.d
        - ./web:/var/www/html

api:
    build: ./api
    links:
        - redis
    expose:
        - 8001
    env_file:
        - ./configs/email.env

redis:
    image: redis
    volumes:
        - data:/data
